### ISSUE TITLE
Unicode error on redirected stdout

### ISSUE THREAD

**Issue by bzamecnik** [rossumai/rossum-api-python-client#6]
```
rossum extract foo.pdf > foo.txt
```

Error:
```
Traceback (most recent call last):
  File "foo.py", line 7, in <module>
    print_summary(invoice)
  File "/Users/bzamecnik/rossum/repos/rossum-api-python-client/rossum/extraction.py", line 183, in print_summary
    print(format_field(field))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 30: ordinal not in range(128)
```

## Solution

Apply `encode('utf-8')` before printing.

**Comment by bzamecnik** [comment]
Actually, the problem occurs only in Python 2 and the solution with `encode()` doesn't work in Python 3.

Better solution for Python 3 is using `PYTHONIOENCODING`:

```bash
PYTHONIOENCODING='utf_8' rossum extract foo.pdf > foo.txt
```
